; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:ATmega328P]
platform = atmelavr
board = atmega328p
framework = arduino
board_build.f_cpu = 1000000UL

;upload_protocol = usbasp
;upload_port = COM3
;upload_command = avrdude -p m328p -U flash:w:$SOURCE:i -c usbasp

;board_fuses.lfuse = 0x62        ; 1 MHz internal RC
;board_fuses.hfuse = 0xD9
;board_fuses.efuse = 0xFF

upload_protocol = custom
;upload_flags = -pm328p -Pusb -B4 -c usbasp
upload_command = "C:\Program Files (x86)\AVRDUDESS\avrdude.exe" -pm328p -Pusb -B 10 -c usbasp -U flash:w:$SOURCE:i
